### ISSUE TITLE
Example

### ISSUE THREAD

**Issue by nsberrow** [maximiliend/docker-wordpress#5]
Can you give an example of what you would run in:

docker run [...] -v /path/to/wp-content:/var/www/html/wp-content [...]

Getting this error:
Unable to find image 'docker-wordpress:latest' locally
docker: Error response from daemon: repository docker-wordpress not found: does not exist or no pull access.

**Comment by maximiliend** [comment]
Sorry for this late reply.

Per example you can use it like this : 

`docker run -v /path/to/wp-content:/var/www/html/wp-content maximiliend/wordpress`

The error you have is because the name of the docker image is incorrect. If you build yourself the image locally it will work, otherwise use maximiliend/wordpress.

I hope this will help you, I will improve the README for the next release.
